[Math-Checker] Add formular comparision
thm-mni-ii/feedbacksystem pull request #1070
Opened 2022-12-22 10:57 UTC by Zitrone44

closes #986

2023-01-19 14:43 UTC, mxsph requested changes

2023-01-19 15:03 UTC, mxsph requested changes
- [x] The coverage of the Math-Parser should be ~100% (see [coverage](https://app.codecov.io/gh/thm-mni-ii/feedbacksystem/tree/i986-formular-comparision/modules/fbs-core))

2023-01-26 13:56 UTC, Zitrone44 commented
> The [coverage](https://app.codecov.io/gh/thm-mni-ii/feedbacksystem/tree/i986-formular-comparision/modules/fbs-core) of the Math-Parser should be ~100% (see coverage)

This can not be archived as their are some lines which are in theory unreachable but are still required to keep the kotline compiler happy.

2023-01-26 15:51 UTC, pdrtzk requested changes

2023-01-26 15:51 UTC, pdrtzk commented on modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4
> +LB: 'lb';
Use _ld_ (logarithmus dualis) as alias for _lb_

2023-01-26 15:51 UTC, pdrtzk commented on modules/fbs-core/math-parser/src/main/antlr/de/thm/ii/fbs/mathParser/Math.g4
> +expr:   (SQR|LB|LN|LG) ' '* expr
What about a unary minus (like **-7** * 3)?

2023-01-26 16:08 UTC, pdrtzk submitted a review, later dismissed

2023-02-02 12:08 UTC, mxsph approved these changes

2023-02-02 12:09 UTC, merged