[Core] Rework ldap authentication
thm-mni-ii/feedbacksystem pull request #1082
Opened 2023-01-05 13:47 UTC by Zitrone44

To test be in the THM VPN and add the following to the `docker-compose.yml` environment section of core.

```yaml
- LDAP_ENABLED=true
```
---
closes #1081

2023-01-10 08:44 UTC, mxsph requested changes

2023-01-10 08:44 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/LoginController.scala
> +    )
I would not put the ldap login in the route `.../api/v1/login/local` but make a new route `.../api/v1/login/` which tries several logins.

2023-01-10 08:44 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/security/LdapService.scala
> +    val response = auth.authenticate(new AuthenticationRequest(username, new Credential(password), "uid"))
`"uid"` should be changeable by a configuration value

2023-01-10 08:44 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/security/LdapService.scala
> +    Option(result.getEntry)
The following options are missing, but were available before the change

```
executor.setTimeLimit(Duration.ofSeconds(TIME_OUT))
executor.setDerefAliases(DerefAliases.ALWAYS)
```

2023-01-10 15:28 UTC, mxsph requested changes
- [x] The New login Route should be added to the Brute force protection

   https://github.com/thm-mni-ii/feedbacksystem/blob/c3671d1065625d2283b8026908fb18cd52a23b03/ws/src/main/scala/de/thm/ii/fbs/security/AntiBruteForceInterceptor.scala#L23

2023-01-12 14:40 UTC, mxsph submitted a review, later dismissed

2023-01-23 12:11 UTC, Medienkunzt reviewed
**BugReport**
Setup test enviroment:
Delete all Docker Containers, Volumes and Images
Add LDAP_ENABLED=true
Run docker-compose up -d --build
Connect to VPN
Enter https://localhost/login

Try to login with my Username and Password
Result -> Internal Server Error (see Logs)

Header:
Request URL: https://localhost/api/v1/login/unified
Request Method: POST
Status Code: 500 
Remote Address: 127.0.0.1:443
Referrer Policy: strict-origin-when-cross-origin

Payload: {
  "username": "jk****",
  "password": "*****************"
}

Response: {"timestamp":1674474697786,"status":500,"error":"Internal Server Error","path":"/api/v1/login/unified"}

[logs.txt](https://github.com/thm-mni-ii/feedbacksystem/files/10479502/logs.txt)

2023-01-24 11:35 UTC, Medienkunzt approved these changes

2023-01-26 11:36 UTC, mxsph approved these changes

2023-01-26 11:36 UTC, merged