Export functionality for multiple tasks or all tasks of a course
thm-mni-ii/feedbacksystem pull request #1091
Opened 2023-01-11 16:21 UTC by timst01

2023-01-19 15:29 UTC, mxsph reviewed
- [ ] Some CI checks fail (see https://github.com/thm-mni-ii/feedbacksystem/actions/runs/3894659533), please fix

2023-02-02 11:21 UTC, mxsph requested changes

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala
> +            logger.info(list.toString())
I would use a map here instead of foreach

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala
> +  @PostMapping(value = Array("/tasks/export"), produces = Array(MediaType.APPLICATION_JSON_VALUE))
```suggestion
  @PostMapping(value = Array("/tasks/export"))
```

This configuration is not necessary.

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala
> +  @GetMapping(value = Array("/tasks/{taskId}/export"), produces = Array(MediaType.APPLICATION_JSON_VALUE))
```suggestion
  @GetMapping(value = Array("/tasks/{taskId}/export"))
```

This configuration is not necessary.

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala
> +  @GetMapping(value = Array("/tasks/export/all"), produces = Array(MediaType.APPLICATION_JSON_VALUE))
```suggestion
  @GetMapping(value = Array("/tasks/export/all"))
```

This configuration is not necessary.

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/export/TaskExportService.scala
> +  }
Instead of passing a list or a TaskId here, you can simply pass a list with an element and always execute `exportTasks`.

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/export/TaskExportService.scala
> +            ConfigExport(cc, checkrunnerSubTaskService.getAll(cc.id), main, secondary)*/
```suggestion
```

2023-02-02 11:21 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/StorageService.scala
> +      new File(path)
```suggestion
      val path = pathToSecondaryFile(config.id).get.toFile
```

2023-02-07 13:34 UTC, mxsph approved these changes

2023-02-07 18:41 UTC, Zitrone44 requested changes
Looks good :+1:

But the export controller does not produce json :smile:. But if the `Accept` Header is set to anything but `application/json` or nothing for example `application/octet-stream` no response will be returned.

2023-02-07 18:41 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/ExportController.scala
>  @GetMapping(path = Array("/api/v1/courses/{cid}"), produces = Array(MediaType.APPLICATION_JSON_VALUE))
```suggestion
@GetMapping(path = Array("/api/v1/courses/{cid}"))
```

2023-02-07 19:02 UTC, Zitrone44 approved these changes

2023-02-07 19:08 UTC, merged