Limit the number of submissions done
thm-mni-ii/feedbacksystem pull request #1101
Opened 2023-01-21 13:16 UTC by SebastianEngl

2023-01-22 10:19 UTC, pdrtzk commented on modules/fbs-core/api/src/main/resources/migrations/14_sql_count_submission.sql
> +INSERT INTO migration (number) VALUES (12);
```suggestion
INSERT INTO migration (number) VALUES (14);
```
The migration number in this statement must be the same as the number used in the file name. 
```suggestion
INSERT INTO migration (number) VALUES (12);
```
Thats  also why the pipline check for migrations fails.

2023-01-24 10:29 UTC, mxsph requested changes

2023-01-24 10:29 UTC, mxsph commented on modules/fbs-core/api/src/main/resources/migrations/14_sql_count_submission.sql
> +
```suggestion
BEGIN;
CREATE TRIGGER checkAttempts before insert on user_task_submission FOR EACH ROW BEGIN
    set @attempts = (SELECT count(submission_id)
          FROM user_task_submission
          WHERE user_id = New.user_id AND task_id = New.task_id);

    set @maxAttempts = (SELECT CASE WHEN attempts IS NULL THEN -1 ELSE attempts END
    FROM task
    WHERE task_id = NEW.task_id);

    IF @maxAttempts != -1 AND @attempts + 1 > @maxAttempts THEN
     signal sqlstate '45000';
    END IF;
END;

ALTER TABLE task ADD COLUMN attempts INTEGER;

```

I would still make some improvements to the trigger (see diff):
  - [ ] if maxAttempts is not set it should be ignored
  - [ ] `DELIMITER` is not needet in jdbc
  - [ ] `submission` is the wrong table (it should be `user_task_submission`
  - [ ] the SQL queries can be truncated

2023-01-27 11:06 UTC, mxsph approved these changes

2023-01-27 14:38 UTC, pdrtzk submitted a review, later dismissed

2023-01-31 08:53 UTC, Zitrone44 requested changes
Works very well :+1:
Just a minor style fix.

2023-01-31 08:53 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/resources/migrations/14_sql_count_submission.sql
> +
```suggestion
```

2023-01-31 08:53 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/resources/migrations/14_sql_count_submission.sql
> +COMMIT;
```suggestion
COMMIT;

```

2023-01-31 08:55 UTC, Zitrone44 approved these changes

2023-01-31 09:04 UTC, merged