web export single task
thm-mni-ii/feedbacksystem pull request #1157
Opened 2023-02-09 16:40 UTC by nicosoethe

resolves #1056

2023-02-13 12:54 UTC, Medienkunzt submitted a review, later dismissed

2023-02-13 14:10 UTC, mxsph requested changes
Instead of adding the suffix `.tar` to the file, it would be better to use `.fbs-export` (like the backend). So as not to confuse users as to why they are receiving a `.tar` file. 

It would be even better if the frontend used the filename that the backend returns in the `content-disposition` header of the http response, as this avoids defining the name in multiple places.

2023-02-13 15:52 UTC, nicosoethe commented
> Instead of adding the suffix `.tar` to the file, it would be better to use `.fbs-export` (like the backend). So as not to confuse users as to why they are receiving a `.tar` file.
> 
I changed this to '.fbs-export"

> It would be even better if the frontend used the filename that the backend returns in the `content-disposition` header of the http response, as this avoids defining the name in multiple places.
>

I am not sure about that. Especially when downloading multiple tasks at the same time, it might be confusing. The name in the response header isn't the same as shown in the front end.

2023-02-13 16:31 UTC, mxsph commented
> I am not sure about that. Especially when downloading multiple tasks at the same time, it might be confusing. The name in the response header isn't the same as shown in the front end.


Yeah, we should take a look at how we handle file downloads/file names in general. With this PR, I am satisfied for now.

2023-02-13 16:32 UTC, mxsph approved these changes

2023-02-14 07:55 UTC, Medienkunzt approved these changes

2023-02-14 07:55 UTC, merged