web export functionality for multiple tasks or all tasks of a course
thm-mni-ii/feedbacksystem pull request #1168
Opened 2023-02-15 10:47 UTC by nicosoethe

resolves #1057

2023-02-28 10:15 UTC, mxsph requested changes
The current implementation downloads multiple files when multiple tasks are selected, which is impractical for a user. The backend provides routes to export multiple tasks into a single file, [`/courses/{cid}/tasks/export`](https://thm-mni-ii.github.io/feedbacksystem/api-docs/#tag/Task/operation/exportTasks) and [`/courses/{cid}/tasks/export/all`](https://thm-mni-ii.github.io/feedbacksystem/api-docs/#tag/Task/operation/exportAllTasks), which should be used by the frontend.

2023-02-28 12:35 UTC, nicosoethe commented
> The current implementation downloads multiple files when multiple tasks are selected, which is impractical for a user. The backend provides routes to export multiple tasks into a single file, [`/courses/{cid}/tasks/export`](https://thm-mni-ii.github.io/feedbacksystem/api-docs/#tag/Task/operation/exportTasks) and [`/courses/{cid}/tasks/export/all`](https://thm-mni-ii.github.io/feedbacksystem/api-docs/#tag/Task/operation/exportAllTasks), which should be used by the frontend.

Multiple tasks will now be downloaded in one file. I did not see those request options in the api-docs while I was working on this issue 2 weeks ago.

2023-03-03 09:48 UTC, Medienkunzt requested changes

2023-03-03 09:48 UTC, Medienkunzt commented on modules/fbs-core/web/src/app/dialogs/export-tasks-dialog/export-tasks-dialog.component.ts
> +    console.log(selectedTasks);
remove console.log

2023-03-03 09:48 UTC, Medienkunzt commented on modules/fbs-core/web/src/app/dialogs/export-tasks-dialog/export-tasks-dialog.component.ts
> +    } */
if this part is not necessary, please remove

2023-03-06 11:14 UTC, Medienkunzt approved these changes

2023-03-06 17:08 UTC, mxsph approved these changes

2023-03-07 08:19 UTC, merged