[Math-Checker] Math-Editor for Submission
thm-mni-ii/feedbacksystem pull request #1199
Opened 2023-03-30 09:13 UTC by Zitrone44

This adds a math input component to the math checker submission page.
---
closes #1137

2023-07-14 11:19 UTC, mxsph submitted a review, later dismissed
- [ ] If you submit something to a task that is not a math task, you get a 403 error.

2023-07-14 12:04 UTC, Zitrone44 commented
> * [ ]  If you submit something to a task that is not a math task, you get a 403 error.

Could you please provider more detailed information about the task in question, like task type, etc.

2023-07-15 18:00 UTC, mxsph requested changes
- [x] @TimonPllkrn The information on how the values are rounded is still a bit strangely placed and should possibly be a bit larger/be highlighted a bit more.

![grafik](https://github.com/thm-mni-ii/feedbacksystem/assets/63304184/fb4ead0c-ece6-421f-8ba9-bf9d51e849f7)

2023-07-17 08:00 UTC, mxsph approved these changes

2023-07-17 09:23 UTC, TimonPllkrn approved these changes

2023-07-17 09:23 UTC, merged