web hide students without submissions in docent view
thm-mni-ii/feedbacksystem pull request #1323
Opened 2023-05-24 14:15 UTC by trKhaled

resolves #1297

2023-06-19 13:12 UTC, TimonPllkrn requested changes
In my opinion, the checkbox is very out of place on this screen. It should be at the top of the table as it only affects that and nothing else. 
Now, for example, when you change the tab, the checkbox is still displayed, but clicking on it has no effect.
I also recommend replacing the checkbox with a switch, because the function is one you want to turn on and off. 
Also, the description of the text should be shown next to it, not just as a tooltip.

Here is a suggestion:
![Frame 15](https://github.com/thm-mni-ii/feedbacksystem/assets/64217916/9a26be77-3ab1-43a5-9219-98e1716c00ca)

2023-06-22 10:07 UTC, TimonPllkrn requested changes
When I click on the filter button, the table slides down. It would be better if the display was a popover, like the menu:

https://material.angular.io/components/menu/overview

2023-06-28 13:38 UTC, TimonPllkrn submitted a review, later dismissed

2023-07-10 09:38 UTC, Medienkunzt approved these changes

2023-07-10 09:38 UTC, merged