remove all tabs in playground
thm-mni-ii/feedbacksystem pull request #1390
Opened 2023-07-11 16:57 UTC by Medienkunzt

resolve #1384 

@TimonPllkrn 
Unfortunately it is not possible to place the button properly next to the tabs. So I have changed the tab control a little bit. See figure. At the moment it does not look 100% beautiful, which is probably due to familiarity. However, in the future, more implementations of new features are easily possible.

![image](https://github.com/thm-mni-ii/feedbacksystem/assets/57532417/640e0afd-545e-4072-88c8-19e7b467f2f1)

2023-07-12 17:05 UTC, Medienkunzt commented
Creation of the new UI design V2
BTN 1 - CloseAllTabs
BTN 2 - DownloadTab
BTN 3 - DownloadAllTabs

![image](https://github.com/thm-mni-ii/feedbacksystem/assets/57532417/acf4fdd1-d3c5-48ce-84fc-d670831111f2)

2023-07-13 08:47 UTC, TimonPllkrn requested changes
There is a mix of english and german languages in the playground. I think we should use only german in our context.
- New Query
- Add your code (default sql)
- Close All Tabs
- Download all Tabs

The placeholder text "Add your code (default sql)" is not displayed in Firefox, maybe you can find a solution here too

2023-07-18 10:15 UTC, TimonPllkrn requested changes

2023-07-18 10:15 UTC, TimonPllkrn commented on modules/fbs-core/web/src/app/page-components/sql-playground/sql-input-tabs/sql-input-tabs.component.ts
> +    console.log(loadedData);
```suggestion
```

2023-08-01 11:30 UTC, merged