Extract classroom
thm-mni-ii/feedbacksystem pull request #574
Opened 2021-09-14 07:32 UTC by snicki13

2021-09-14 08:33 UTC, mxsph reviewed
Already a couple of notes:

- Shouldn't we add the `digital-classroom` to the `docker-compose.yml` (as image with `docker pull ghcr.io/thm-mni-ii/digital-classroom:master`)? So that the FBS can be tested more easily during development.

2021-09-14 08:33 UTC, mxsph commented on docker-compose.yml
> +      - BBB_URI=http://host.docker.internal:8085
For `host.docker.internal` to work under linux the following must be added to the `http` container in `docker-compose.yml`:

```yml
extra_hosts:
      - "host.docker.internal:host-gateway"
```

2021-09-14 08:33 UTC, mxsph commented on .github/workflows/docker-image.yml
> +      run: docker push thmmniii/http:classroom
We should remove this file before merging

2021-12-06 14:30 UTC, mxsph requested changes
- [ ] When I try to join the classroom I get this error:

```
Could not create JAXBContext for class [class de.thm.ii.fbs.model.classroom.JoinRoomBBBResponse]: Implementation of JAXB-API has not been found on module path or classpath.; nested exception is javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath. - with linked exception:[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
```
- [ ] The conference settings should be removed (since they no longer work anyway).
  
  ![grafik](https://user-images.githubusercontent.com/63304184/144861165-86ef0d2a-08b5-458c-8329-110ddc2dc8ca.png)

- [ ] A user with the global role `Admin` should have the role `DOCENT` in all courses in the Digital Classroom.
- [ ] A user with the Global role 'Moderator' should have the role 'TUTOR' in all courses in the Digital Classroom.

2021-12-06 14:30 UTC, mxsph commented on web-gui/src/app/page-components/course-detail/course-detail.component.ts
> +              private conferenceService: ExternalClassroomHandlingService,
This service is no longer used

2021-12-06 14:30 UTC, mxsph commented on web-gui/src/app/service/external-classroom.service.ts
> +                     private mDialog: MatDialog,
These three service are no longer used

2021-12-06 14:30 UTC, mxsph commented on web-gui/src/app/service/external-classroom-handling-service.ts
> +}
This service is no longer used (If you remove this service from the files which only import it, but do not use it)

2021-12-06 14:30 UTC, mxsph commented on web-gui/src/app/util/rx-stomp.ts
>  import {Subscription} from 'stompjs';
@Zitrone44  when this file is removed, several compiler errors occur (see [here](https://github.com/thm-mni-ii/feedbacksystem/runs/4425128466?check_suite_focus=true#step:7:122)) which have nothing to do with it, any idea why?

2021-12-06 23:50 UTC, snicki13 commented
I don't want to know.

2021-12-06 23:53 UTC, mxsph commented on web-gui/src/app/util/rx-stomp.ts
>  import {Subscription} from 'stompjs';
I have found the error/a solution (see ee429f7642cd82a3ce1156d9554dac08ea94db9f)

2021-12-07 00:20 UTC, mxsph requested changes
I have found another bug where it is possible to end up in two different classrooms in the same course:

User 1: Create & Join Course
User 2: Join Course
User 1: Open Classroom
User 1: Close Classroom
restart digital-classroom (`docker-compose restart digital-classroom`)
User 1: Open Classroom
User 2: Open Classroom

Now the two users are in two different classrooms

2021-12-07 00:37 UTC, snicki13 commented
> I have found another bug where it is possible to end up in two different classrooms in the same course:
> 
> User 1: Create & Join Course User 2: Join Course User 1: Open Classroom User 1: Close Classroom restart digital-classroom (`docker-compose restart digital-classroom`) User 1: Open Classroom User 2: Open Classroom
> 
> Now the two users are in two different classrooms

good catch

2021-12-07 01:24 UTC, mxsph approved these changes

2021-12-07 01:31 UTC, merged