Calculation for the rate of edited task added
thm-mni-ii/feedbacksystem pull request #590
Opened 2021-11-09 11:16 UTC by Jonas960

resolves #589

2021-11-11 09:40 UTC, Zitrone44 approved these changes
:+1:

2021-11-12 10:51 UTC, mxsph requested changes
During testing I found a few errors:

- [ ] When opening the subtasks the diagram is moved to the right and down. It would be better if the diagram stays on the same position.
  
  ![error-1](https://user-images.githubusercontent.com/63304184/141455255-c1a9b708-24f9-43d2-861a-2bddbb23f471.gif)


- [ ] If you don't click on the bars in the diagram, you get to the subtasks, but the numbers don't change.

  ![error-2](https://user-images.githubusercontent.com/63304184/141455311-051e0825-8084-4c47-b6bb-4081f63225ea.gif)

- [ ] There is an error in the calculation of the statistics (see gif). Shouldn't it be that `Test` and `Test 3` have only one bar? (Since no one has yet passed the task).  

  ![error-3](https://user-images.githubusercontent.com/63304184/141455361-215c72a6-19cd-4d95-b6a2-ed87d55df7a5.gif)

2021-11-12 10:51 UTC, mxsph commented on web-gui/src/app/page-components/course-detail/course-results/results-statistic/results-statistic.component.ts
> +            if (acc[t.task.name] == null) acc[t.task.name] = [];
```suggestion
            if (!acc[t.task.name]) acc[t.task.name] = [];
```

2021-11-19 16:41 UTC, Jonas960 commented
@mxsph I have implemented your change requests. Please check if it is fine now.

2021-11-22 14:09 UTC, mxsph requested changes
Looks good so far :+1: , but there is still one problem:

Since you use the `name` of a task to save the calculation (and also to save which task is selected) statistics for tasks with the same name are calculated incorrectly. For this you should use the task ID, as this is unique.

2021-11-22 15:51 UTC, Jonas960 commented
![grafik](https://user-images.githubusercontent.com/83070806/142892327-a335e464-60e6-47d0-a074-397bfe20ea5c.png)
![grafik](https://user-images.githubusercontent.com/83070806/142892405-e6914970-b501-4bad-bde5-c521b7adb1bc.png)

@mxsph I fixed it.

2021-11-22 20:16 UTC, mxsph commented
> @mxsph I fixed it.

The calculation looks good now :+1:

However, there is still the same problem with the display of subtasks since you use there also only the name.

2021-11-25 09:51 UTC, Jonas960 commented
@mxsph The presentation of the subtasks is now based on the ids of the parent tasks. I tested it with some tasks and it worked for me.

2021-11-25 18:28 UTC, mxsph approved these changes

2021-11-25 18:33 UTC, merged