Possibility to clean up a course
thm-mni-ii/feedbacksystem pull request #607
Opened 2021-12-22 13:20 UTC by Jonas960

resolves #595

2021-12-22 14:05 UTC, mxsph requested changes
Looks good so far :+1: 

There are only a few small things that still should be adjusted:

- [x] You should add the two new api routes to the API specification ([swagger.yml](https://github.com/thm-mni-ii/feedbacksystem/blob/2770ef11a1b050cecd9289e9661112cf7c0c92b4/swagger.yml)).

2021-12-22 14:05 UTC, mxsph commented on ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseRegistrationService.scala
> +      * Deregister all users except the current user .
```suggestion
      * Deregister all users except the current user.
```

2021-12-22 14:05 UTC, mxsph commented on web-gui/src/app/service/course-registration.service.ts
> +    return this.http.put<void>(`/api/v1/courses/${cid}/deregisterrole`, {roleName: roleName});
```suggestion
    return this.http.put<void>(`/api/v1/courses/${cid}/deregisterrole`, {roleName});
```

2021-12-22 15:36 UTC, Jonas960 commented
@mxsph I have implemented your suggestions

2021-12-22 21:57 UTC, mxsph reviewed
- [x] The buttons should be displayed at the top (so that they do not disappear when there are too many users).
  ![grafik](https://user-images.githubusercontent.com/63304184/147158991-d18cefa6-33e4-4d89-9cb3-73956bde847a.png)
- [x] I find the color of the buttons a bit too bright. I would change the `red` to the color of the header (`#405e9a`)
  ![grafik](https://user-images.githubusercontent.com/63304184/147159437-dd19bc92-9af4-4ed8-831e-08e99918836a.png)
- [x] The rights check in the backend has a part that is superfluous and there is a bug, which leads to the situation that everyone can remove all users. I have already fixed this (see 0b610009ca61b41dd6139944ef49a9a119ec15cc).

2021-12-23 12:01 UTC, mxsph approved these changes

2021-12-23 12:39 UTC, Zitrone44 approved these changes

2021-12-23 12:40 UTC, merged