statistics should exclude teachers and tutors
thm-mni-ii/feedbacksystem pull request #608
Opened 2022-01-02 20:00 UTC by Jonas960

2022-01-03 09:15 UTC, Zitrone44 requested changes
Works good :+1:

But i would recommend reducing repetition by dynamically building the query instead of completely copying it for `getStudResult`.

2022-01-03 19:44 UTC, Jonas960 commented
@Zitrone44 The query is now dynamically generated. The query must now be called with the cid and the role numbers (from, to).

2022-01-04 08:25 UTC, Zitrone44 requested changes
Like @mxsph suggested at the meeting default values should be added to `getAll`.

2022-01-04 08:25 UTC, Zitrone44 commented on ws/src/main/scala/de/thm/ii/fbs/services/persistence/CourseResultService.scala
> +  def getAll(cid: Int, from: Int, to: Int): List[CourseResult] = DB.query("""
```suggestion
  def getAll(cid: Int, from: Int = 0, to: Int = 2): List[CourseResult] = DB.query("""
```

2022-01-04 08:25 UTC, Zitrone44 commented on ws/src/main/scala/de/thm/ii/fbs/controller/CourseResultController.scala
> +      evaluationResultService.evaluate(evaluationContainerService.getAll(cid), courseResultService.getAll(cid, 0, 2))
```suggestion
      evaluationResultService.evaluate(evaluationContainerService.getAll(cid), courseResultService.getAll(cid))
```

2022-01-04 08:25 UTC, Zitrone44 commented on ws/src/main/scala/de/thm/ii/fbs/controller/CourseResultController.scala
> +      courseResultService.getAll(cid, 0, 2)
```suggestion
      courseResultService.getAll(cid)
```

2022-01-04 14:49 UTC, Zitrone44 approved these changes

2022-01-04 14:49 UTC, merged