Remove snackbar
thm-mni-ii/feedbacksystem pull request #611
Opened 2022-01-20 11:47 UTC by hermannlallah

2022-01-21 13:14 UTC, Zitrone44 requested changes
In principle correct, but not the success snackbars in `web-gui/src/app/page-components/user-management` should be replaced, but the confirmation snackbars in `web-gui/src/app/tool-components/participants`. Sorry if that wasn't clear from the issue.

2022-04-07 14:12 UTC, mxsph requested changes

2022-04-07 14:12 UTC, mxsph commented on web-gui/src/app/tool-components/participants/participants.component.ts
> +            // this.snackBar.open('Alle Tutoren wurden entfernt', 'ok', {duration: 3000});
```suggestion
```

2022-04-07 14:12 UTC, mxsph commented on web-gui/src/app/tool-components/participants/participants.component.ts
> +              // this.snackBar.open('Teilnehmer hinzugefügt.', 'ok', {duration: 3000});
```suggestion
```

2022-04-07 14:13 UTC, mxsph commented on web-gui/src/app/tool-components/participants/participants.component.ts
> +            this.openDialog('Erfolgreich !!!', 'Alle Studierenden wurden entfernt');
```suggestion
```

2022-04-20 22:14 UTC, mxsph requested changes
- [x] When deleting the checkers, a snack bar is still shown:
![Peek 2022-04-20 23-40](https://user-images.githubusercontent.com/63304184/164333606-d5c05afd-9c85-4208-bc93-330f07f01ca0.gif)

2022-04-20 22:14 UTC, mxsph commented on web-gui/src/app/tool-components/confirmation-dialog/confirmation-dialog.component.ts
> +  cancelButtonText = 'Cancel';
These texts should be in German

2022-04-20 22:14 UTC, mxsph commented on web-gui/src/app/tool-components/participants/participants.component.ts
> +  private openDialog(title: string, message: string) {
Since the `title` is never displayed, it can be removed.

2022-04-20 22:14 UTC, mxsph commented on web-gui/src/app/tool-components/confirmation-dialog/confirmation-dialog.component.ts
> +
There is already a component for displaying a dialog (https://github.com/thm-mni-ii/feedbacksystem/blob/eda2d80b3d2667bd2681b5ce0d485fa1142474ec/web-gui/src/app/dialogs/confirm-dialog/confirm-dialog.component.ts). Why is a new one being created here? Shouldn't it just be possible to use this one?

2022-04-27 11:22 UTC, Jonas960 commented
@mxsph I don't know why a second dialog component was created. I changed it to use the existing one. That works without any problems. I have also implemented your change requests. For the three functions of deleting all students, all tutors and all users, I have implemented a double confirmation to protect the user.

2022-08-01 11:15 UTC, mxsph approved these changes

2022-08-01 12:49 UTC, Zitrone44 approved these changes

2022-08-01 12:49 UTC, merged