Default values for forms
thm-mni-ii/feedbacksystem pull request #615
Opened 2022-02-04 19:38 UTC by hermannlallah

2022-02-07 12:59 UTC, mxsph requested changes
There are still some problems:

- [x] Filling in the order does not work:
  
  ![Peek 2022-02-07 13-43](https://user-images.githubusercontent.com/63304184/152791712-3b246f92-026b-4bf5-a29b-442420b2997a.gif)

- [x] It would be practical if the submission type 'Text' is selected by default when creating a task.

2022-02-07 12:59 UTC, mxsph commented on web-gui/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts
> +
```suggestion
```

2022-02-07 12:59 UTC, mxsph commented on web-gui/src/app/dialogs/task-new-dialog/task-new-dialog.component.ts
> +currentDateAndOneMonthLater.setMonth(currentDateAndOneMonthLater.getMonth() + 1);
Generating the date here works, but leads to the problem that it is only generated once and therefore the time does not correspond to the current time. Here you should define a function that generates and returns the date:

![grafik](https://user-images.githubusercontent.com/63304184/152792536-7ee79ae9-9a40-45a9-b0f6-23fa4f7f2bd4.png)

2022-04-05 07:32 UTC, Jonas960 commented
@mxsph The default values are now filled correctly. For filling the order, I took '1' as the default value. If this value is not correct, let me know

2022-04-05 11:52 UTC, mxsph requested changes
> @mxsph The default values are now filled correctly. For filling the order, I took '1' as the default value. If this value is not correct, let me know

- [x] Basically, `1` is the correct default value, but the order of the previous `plus 1` would make the most sense.

- [ ] If you specify a `0` as order, the frontend complains that not all fields have been filled in, this should be adjusted.

- [x] For the PR to be ready, the error from the comment above https://github.com/thm-mni-ii/feedbacksystem/pull/615#discussion_r800629457 should also be fixed.

2022-04-07 14:06 UTC, mxsph requested changes

2022-04-07 14:07 UTC, mxsph approved these changes

2022-04-07 14:14 UTC, merged