Export tasks
thm-mni-ii/feedbacksystem pull request #616
Opened 2022-02-09 19:20 UTC by hermannlallah

2022-02-21 10:50 UTC, Zitrone44 requested changes
Looks good so far but. I would:
* [x] show the download buttons for lecturers only
* [x] give downloaded file a name (not just `download`)
* [x] button position too prominent for rare used function (maybe move into view displayed when task is selected from the list?)

2022-05-07 18:01 UTC, hermannlallah commented
changes implemented. i didn't know where to place the button so i leave it at its initial position.

2022-05-11 10:02 UTC, Zitrone44 approved these changes

2022-08-03 17:34 UTC, mxsph approved these changes

2022-08-03 17:35 UTC, merged