Excel checker
thm-mni-ii/feedbacksystem pull request #637
Opened 2022-05-05 08:36 UTC by mxsph

resolves #636

2022-05-08 20:06 UTC, Jonas960 commented
@mxsph Looks good. However, I found an error message that only returns null. This happens if you miss the key "outputFields" in the config json. 
![grafik](https://user-images.githubusercontent.com/83070806/167313834-7ef9585e-16f7-4510-a9b8-a95942376c13.png)
![grafik](https://user-images.githubusercontent.com/83070806/167313846-bdc3d6ea-41b6-470d-87ad-c0541d816ab4.png)

2022-05-11 11:45 UTC, Zitrone44 requested changes
Works very well :+1:

I only found one problem, if a new checker is created it is not shown in the checker list until the page is reloaded:
![Peek 2022-05-11 13-33](https://user-images.githubusercontent.com/5428264/167841443-0a8179ad-c21f-471c-8ef7-0217b5d2d7f0.gif)

2022-05-19 08:31 UTC, Jonas960 approved these changes
Frontend component looks fine.

2022-06-02 16:07 UTC, Zitrone44 approved these changes

2022-06-02 16:07 UTC, merged