I605 category result overview clean up fertig
thm-mni-ii/feedbacksystem pull request #640
Opened 2022-05-18 13:18 UTC by djoko1989

#605

2022-05-21 13:40 UTC, Zitrone44 requested changes
Looks good. Only the changes in the `results` component that add comments should be removed and added in another pull request if necessary. Since they are not part of the issue #605.

2022-05-21 17:00 UTC, djoko1989 commented
I have only worked on 4 issues and don't know the others so I have separated each of my issues into a branch

2022-05-21 17:01 UTC, djoko1989 commented
here it is just a matter of sorting out the results of the categories

2022-05-21 17:33 UTC, djoko1989 commented
I think, now all was removed

2022-05-24 07:55 UTC, Zitrone44 submitted a review, later dismissed

2022-05-24 07:56 UTC, Zitrone44 requested changes

2022-05-24 07:56 UTC, Zitrone44 commented on web-gui/src/app/page-components/results/results.component.ts
> +  }
```suggestion
```
changes in this file should also be reverted.

2022-05-25 06:40 UTC, Zitrone44 approved these changes

2022-08-18 13:15 UTC, closed without merging