[API] Mark tasks as mandatory bonusadditional etc
thm-mni-ii/feedbacksystem pull request #773
Opened 2022-09-20 13:41 UTC by pdrtzk

2022-09-20 14:01 UTC, pdrtzk commented
Issue #704 can be implemented once this PR is merged.

2022-09-22 09:15 UTC, Zitrone44 requested changes
Works :+1:

I would suggest that we validate `requirementType` to be either `madatory` or `optional`/`bonus`. And a few other suggestions:

2022-09-22 09:15 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/resources/migrations/06_task_requirement_type.sql
> +    add requirement_type VARCHAR(200) not null;
* do we really need 200 characters here?
* a default value should be set to have already existing Task return the correct `requirementType` (`DEFAULT 'mandatory'`)

2022-09-22 09:15 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +        body.retrive("requirementType").asText()
maybe we should validate here if `requirementType` has a valid value.

2022-09-23 06:31 UTC, Zitrone44 approved these changes

2022-09-23 06:32 UTC, merged