Show tasks only for lecturers/tutors
thm-mni-ii/feedbacksystem pull request #814
Opened 2022-10-02 17:45 UTC by timst01

I did not change getTaskResult because i think the result is only accessed trough the Task, so if the Task is not visible the results can not be accessed

2022-10-04 07:16 UTC, mxsph requested changes
Some of the commits should not be in this PR as they belong to the PR 
#754. You could remove them for example with an ineractive rebase (see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_changing_multiple) or cherry-pick (see https://git-scm.com/docs/git-cherry-pick).

2022-10-06 11:29 UTC, pdrtzk commented
The commits that do not belong to the PR should be removed now.

2022-10-06 12:15 UTC, pdrtzk requested changes
- [ ] Update the [api documentation](https://github.com/thm-mni-ii/feedbacksystem/blob/dev/modules/fbs-core/api/api-docs.yml).
- [ ] Instead of checking if the task `isPublic` check if it `isPrivate`, which should be default `false`.
- [ ] In the api requests `isPrivate` should be optional, so that frontend still works.

2022-10-11 10:49 UTC, pdrtzk requested changes
There is currently a bug with the authorization caused by this line:
https://github.com/thm-mni-ii/feedbacksystem/blob/991614684efd5eef05339d0bcb73f6ab09716b67/modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala#L72

Because the `getOne()` function in filter is called on each object in the stream, the authorization inside of `getOne()` is called too often.

You can outsource the following code out of `getOne()` and inside a new function. This must be called instead of the code then and also in the filter.

https://github.com/thm-mni-ii/feedbacksystem/blob/991614684efd5eef05339d0bcb73f6ab09716b67/modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala#L114-L134

2022-10-12 08:03 UTC, pdrtzk approved these changes
Works now as expected.  👍

2022-10-18 09:43 UTC, mxsph requested changes
- [ ] If a task in a course is `private`, no tasks are displayed for a student. Because the `/{cid}/tasks/results` then throws a `403` error.
- [ ] Private assignments should not only be returned to administrators, but also to "course" lecturers.

2022-10-20 10:17 UTC, mxsph requested changes
- [x] It should not be possible for a user to make a submission to a private task.
- [ ] It should not be possible for a user to retrieve results from a private task.

2022-10-20 10:17 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +    val someCourseRole = courseRegistration.getParticipants(cid).find(_.user.id == auth.id).map(_.role)
You should improve this code as it always has to search all users in the course. For this I would add a new method in the `courseRegistration` service which returns the role of a user in the course (for this you can orientate yourself on the function `getCoursePrivileges`).

2022-10-20 10:17 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +    val someCourseRole = courseRegistration.getParticipants(cid).find(_.user.id == auth.id).map(_.role)
You should improve this code as it always has to search all users in the course. For this I would add a new method in the `courseRegistration` service which returns the role of a user in the course (for this you can orientate yourself on the function `getCoursePrivileges`).

2022-10-20 10:17 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
>    }
I would solve the problem a bit differently and not use a `try catch` but pass a parameter to the method `getTaskById` which determines whether an exception is thrown or not.

2022-10-25 11:00 UTC, mxsph approved these changes

2022-10-25 11:22 UTC, Zitrone44 approved these changes

2022-10-25 11:23 UTC, merged