web add semester field to courses and auto archive old courses
thm-mni-ii/feedbacksystem pull request #920
Opened 2022-11-07 10:11 UTC by Medienkunzt

resolves #610

2022-11-07 11:13 UTC, Medienkunzt reviewed
~wait till API is fixed (see #933)~ resolved by #933

2022-11-08 13:45 UTC, Medienkunzt reviewed
#610 is working with the fix #933 

This PR is ready for review @TimonPllkrn

2022-11-28 09:29 UTC, TimonPllkrn requested changes
works very well 👍🏼 

i think the checkbox for selecting a semester unnecessary. I always try to click directly in the dropdown and then have to select the checkbox first.
i would rather give the dropdown a "no semester" item.

2022-11-29 10:11 UTC, TimonPllkrn approved these changes

2022-11-29 10:11 UTC, merged