Update storage service to use minio instead of local fs
thm-mni-ii/feedbacksystem pull request #975
Opened 2022-11-22 11:45 UTC by timst01

2022-11-24 12:58 UTC, mxsph requested changes

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +    uploadFile("main-file",
I would store the name of the `main-file` in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +    getFile(storageService.pathToMainFile)("main-file", cid, tid, ccid, req, res)
I would store the name of the `main-file` in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +    uploadFile("secondary-file",
I would store the name of the `secondary-file` in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +    getFile(storageService.pathToSecondaryFile)("secondary-file", cid, tid, ccid, req, res)
I would store the name of the `secondary-file` in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +          val bucketName = "tasks"
I would store the name of the bucket in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +            .`object`("/" + tid.toString + "/" + fileName).filename(tempDesc.toString).build())
The creation of the new bucket should be created in the storageServerice

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/CheckerConfigurationController.scala
> +            }
the `isInBlockStorage` check should be in the storageService

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/SubmissionController.scala
> +            //storageService.storeSolutionFile(submission.id, tempDesc)
```suggestion
```

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +              spreadsheetFile = new File(path)
The check `isInBlockStorage` shold be in the `storageService`

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +            var spreadsheetFile: File = new File(tempFile)
The Temp file should be created with `Files.createTempFile` and the Temp file should be deletet after usage

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/controller/TaskController.scala
> +              storageService.getFileFromBucket("tasks", s"${task.id}/main-file", tempFile)
I would store the name of the `main-file` in as a static member of a global object

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/RemoteCheckerService.scala
> +      //secFile = storageService.getFileFromBucket("tasks", s"${cc.taskId}/secondary-file")
```suggestion
```

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/RemoteCheckerService.scala
> +    //val subTaskPath = storageService.getFileFromBucket("submissions", s"$sid/subtask-file")
```suggestion
```

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetFileService.scala
> +    }
I would move the If statment to the storage service so that you don't have to write it again and again.

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/excel/SpreadsheetFileService.scala
> +    }
I would move the If statment to the storage service so that you don't have to write it again and again.

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala
> +    }
I would move the If statment to the storage service so that you don't have to write it again and again.

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala
> +      //spreadsheetFile = storageService.getFileFromBucket("tasks", s"${cc.taskId}/main-file")
```suggestion
```

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala
> +    }
I would move the If statment to the storage service so that you don't have to write it again and again.

2022-11-24 12:58 UTC, mxsph commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/checker/math/SpreadsheetCheckerService.scala
> +      //submissionFile = storageService.getFileFromBucket("tasks", s"${cc.taskId}/main-file")
```suggestion
```

2022-12-01 13:35 UTC, mxsph requested changes
- [x]  There is a race condition when the configuration bucket is first created (I would create it, if not present, after minio initialisation):

<details>
<summary>Stack Trace</summary>

```
 io.minio.errors.ErrorResponseException: Your previous request to create the named bucket succeeded and you already own it.
feedbacksystem-core-1  |        at io.minio.MinioClient.execute(MinioClient.java:767) ~[minio-8.0.0.jar:8.0.0]
feedbacksystem-core-1  |        at io.minio.MinioClient.makeBucket(MinioClient.java:2269) ~[minio-8.0.0.jar:8.0.0]
feedbacksystem-core-1  |        at de.thm.ii.fbs.services.persistence.StorageService.storeConfigurationFileInBucket(StorageService.scala:109) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  |        at de.thm.ii.fbs.controller.CheckerConfigurationController.uploadFile(CheckerConfigurationController.scala:258) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  |        at de.thm.ii.fbs.controller.CheckerConfigurationController.updateMainFile(CheckerConfigurationController.scala:202) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  |        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
feedbacksystem-core-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
feedbacksystem-core-1  |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:684) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
feedbacksystem-core-1  |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:50) ~[cas-client-core-3.5.1.jar:3.5.1]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:71) ~[cas-client-core-3.5.1.jar:3.5.1]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embe [...]

2023-01-03 13:23 UTC, Zitrone44 requested changes
Looks good :+1: just two things:

2023-01-03 13:23 UTC, Zitrone44 commented on modules/fbs-core/api/src/main/scala/de/thm/ii/fbs/services/persistence/CheckrunnerConfigurationService.scala
> +    " checker_type_information, is_in_block_storage " +
Hier tritt ein Fehler auf: 
<details>

<summary>Stacktrace</summary>

```
feedbacksystem-core-1  | java.sql.SQLIntegrityConstraintViolationException: Column 'is_in_block_storage' in field list is ambiguous
feedbacksystem-core-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.19.jar:8.0.19]
feedbacksystem-core-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
feedbacksystem-core-1  | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
feedbacksystem-core-1  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
feedbacksystem-core-1  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.19.jar:8.0.19]
feedbacksystem-core-1  | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-4.0.3.jar:na]
feedbacksystem-core-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:815) ~[spring-jdbc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at de.thm.ii.fbs.util.DB$.query(DB.scala:33) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  | 	at de.thm.ii.fbs.services.persistence.CheckrunnerConfigurationService.getAllForSubmission(CheckrunnerConfigurationService.scala:35) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  | 	at de.thm.ii.fbs.controller.CheckerApiController.getSubmission(CheckerApiController.scala:55) ~[fbs-core.api-1.0-SNAPSHOT-plain.jar:na]
feedbacksystem-core-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
feedbacksystem-core-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
feedbacksystem-core-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
feedbacksystem-core-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:50) ~[cas-client-core-3.5.1.jar:3.5.1]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:71) ~[cas-client-core-3.5.1.jar:3.5.1]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
feedbacksystem-core-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0 [...]

2023-01-03 13:23 UTC, Zitrone44 commented on modules/fbs-core/api/build.gradle
> +    compileOnly 'io.minio:minio:8.0.0'
```suggestion
```

implementation beinhaltet `compileOnly`.

2023-01-04 09:49 UTC, mxsph approved these changes

2023-01-04 09:55 UTC, Medienkunzt approved these changes

2023-01-04 09:59 UTC, merged